<?php
// module/Album/view/album/album/add.phtml:

$title = 'Add new album';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form->setAttribute('action', $this->url('agenda', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('agenda_id'));
echo $this->formRow($form->get('agenda_nome'));
echo $this->formRow($form->get('agenda_fixo'));
echo $this->formRow($form->get('agenda_celular'));
echo $this->formRow($form->get('agenda_email'));

echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();