<?php
// module/Album/view/album/album/index.phtml:

$title = 'Agenda de Contatos';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('agenda', array('action'=>'add'));?>">Add new contact</a>
</p>

<table class="table">
<tr>
	<th>Id</th>
    <th>Nome</th>
    <th>Telefone Fixo</th>
    <th>Telefone Celular</th>
    <th>e-Mail</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($agenda as $agendas) : ?>
<tr>

	    
	<td><?php echo $this->escapeHtml($agendas->agenda_id);?></td>
	<td><?php echo $this->escapeHtml($agendas->agenda_nome);?></td>
    <td><?php echo $this->escapeHtml($agendas->agenda_fixo);?></td>
    <td><?php echo $this->escapeHtml($agendas->agenda_celular);?></td>
    <td><?php echo $this->escapeHtml($agendas->agenda_email);?></td>
    <td>
        <a href="<?php echo $this->url('agenda',array('action'=>'edit', 'id'=>$agendas->agenda_id));?>">Edit</a>
        <a href="<?php echo $this->url('agenda',array('action'=>'delete', 'id'=>$agendas->agenda_id));?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>